# Generated by Django 6.0.2 on 2026-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('f', 'Foodie'), ('c', 'Chef')], default='f', max_length=10),
        ),
    ]
